server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbstudent
    username: root
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  application:
    name: Spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 252281711@qq.com
    password: omtfomvlnuqgbgfc
    default-encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://hepengfei:123456@localhost:27017/admin
mybatis:
  type-aliases-package: com.hello.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
mail:
  fromMail:
    addr: 252281711@qq.com